# Shell variables
# Generated by 'wal'
wallpaper='up1.jpg'

# Special
background='#0d0f0f'
foreground='#f5fffe'
cursor='#f5fffe'

# Colors
color0='#0d0f0f'
color1='#81817D'
color2='#5A8F76'
color3='#ABB5B1'
color4='#71968B'
color5='#90A29B'
color6='#60C493'
color7='#ccdbd3'
color8='#1f2424'
color9='#b8b892'
color10='#65c99a'
color11='#c7ffea'
color12='#81d4bb'
color13='#a7e6cd'
color14='#69ffbf'
color15='#f5fffe'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
