# Shell variables
# Generated by 'wal'
wallpaper='abst8.jpg'

# Special
background='#04142D'
foreground='#d8ffff'
cursor='#d8ffff'

# Colors
color0='#04142D'
color1='#5AA5B1'
color2='#246E8D'
color3='#EAAE78'
color4='#196C8A'
color5='#5F6F88'
color6='#2D94A9'
color7='#a5d1da'
color8='#062452'
color9='#63e3f7'
color10='#2393c2'
color11='#ffe084'
color12='#1591be'
color13='#6c8dbf'
color14='#2cc9e9'
color15='#d8ffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
