# Shell variables
# Generated by 'wal'
wallpaper='vintage1.jpg'

# Special
background='#03091D'
foreground='#ffffde'
cursor='#ffffde'

# Colors
color0='#03091D'
color1='#BB4B38'
color2='#469661'
color3='#9F6356'
color4='#1D3153'
color5='#5A5F60'
color6='#245563'
color7='#d2c6a9'
color8='#051342'
color9='#ff5638'
color10='#4cd179'
color11='#de765f'
color12='#1e3d73'
color13='#698388'
color14='#257389'
color15='#ffffde'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
